branch-defaults:
  main:
    environment: salish-distribution
    group_suffix: null
global:
  application_name: salish-distribution
  branch: null
  default_ec2_keyname: salish-distro
  default_platform: Ruby 3.0 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
